// Generated by CoffeeScript 1.4.0
(function() {
  var Crontab, crontab_root;

  Crontab = require('../index').Crontab;

  crontab_root = new Crontab();

  crontab_root.set('*/2', '1', '20-30/2', '*', '2,4,6', function() {
    return console.log(new Date().toISOString());
  });

  crontab_root.set('10', '10-22/2', '*', '*', '*', function() {
    return process.nextTick(function() {
      return console.log('I am doing the thing.');
    });
  });

  crontab_root.run();

}).call(this);
