// Generated by CoffeeScript 1.4.0
(function() {
  var Task, login_task, validate_login;

  Task = require('../index').Task;

  validate_login = function(username, password, complete) {
    console.log(username);
    console.log(password);
    if (username === 'Avicha' && password === '123456' || username === 'Yi' && password === '654321') {
      return process.nextTick(function() {
        return complete(1, 0);
      });
    } else {
      return process.nextTick(function() {
        return complete(0, 1);
      });
    }
  };

  login_task = new Task('handle the user login', 100, validate_login);

  login_task.push('Avicha', '123456');

  login_task.pushAll([['Avicha', '123456'], ['Yi', '654321'], ['other_user', 'their_password']]);

  login_task.end(function() {
    return process.exit(0);
  });

}).call(this);
