// Generated by CoffeeScript 1.4.0
(function() {
  var Task, log, log_task, _i, _results;

  Task = require('../index').Task;

  log = function(i, complete) {
    console.log(i);
    return complete(1, 0);
  };

  log_task = new Task('console.log', 5, log);

  log_task.push(1);

  log_task.push(2);

  log_task.pushAll((function() {
    _results = [];
    for (_i = 100; _i >= 1; _i--){ _results.push(_i); }
    return _results;
  }).apply(this));

  log_task.end(function(infos) {
    return console.log(infos);
  });

}).call(this);
